### ISSUE TITLE
vecCentreOfMassOffset Format clarify please

### ISSUE THREAD

**Issue by treboR-0** [Bluethefurry/FiveM-Handling-Editor-Example#2]
how to reproduce this:
< vecCentreOfMassOffset x="0.000000" y="0.000000" z="-5.000000" / >

SetVehicleHandlingData(veh,"vecCentreOfMassOffset", vector3(0.0, 0.0, -5.0)) no function

**Comment by Blumlaut** [comment]
.. what?

**Comment by treboR-0** [comment]
In handling.meta this sets the vehicle's center of mass below the surface of the ground.
< vecCentreOfMassOffset x="0.000000" y="0.000000" z="-5.000000" / >

But when set as another parameter this and other handlings using vector3 such as vecInertiaMultiplier do not do anything at all. Are you able to make these work with your system, if so please provide a functioning example as they are as confusing to me as they are very important. Life without them may not be worth living!
SetVehicleHandlingData(veh,"vecCentreOfMassOffset", vector3(0.0, 0.0, -5.0)) --should work, but does not work

**Comment by treboR-0** [comment]
:-)

**Comment by Blumlaut** [comment]
center of mass offset is apparently hardcoded and cannot be changed. wontfix/cantfix
